### ISSUE TITLE
AMT templates issues

### ISSUE THREAD

**Issue by NicolasAG** [facebookresearch/clutrr#13]
This is a list of issues on the AMT templates:

Known issues:
- Some templates are not in the correct `relation/gender` category.
- Some templates have the wrong pronouns, eg: `ENT_0_female` with `he`/`him`/`his`.
- Some templates have `Worker: ` as prefix.
- Some templates are not complete sentences.

| template | train or test file | listed as | should be | corrected |
| --- | --- | --- | --- | ---|
| _ENT_1_female and ENT_0_male ._ | train | `wife/male-female` | removed? | ⛔ |
|_ENT_1_female and ENT_0_male ._ | train | `granddaughter/male-female` | removed? | ⛔ |
| _ENT_1_male and his son ENT_0_male went to look at cars. ENT_1_male ended up buying the Mustang._ | test | `son/male-male` | `father/male-male` | ⛔ |
| _ENT_1_female is a girl with a grandmother named ENT_0_female ._ | train | `grandmother/female-female` | `granddaughter/female-female` | ⛔ |
| _ENT_1_female went to visit her grandmother , ENT_0_female , in the retirement home ._ | train | `grandmother/female-female` | `granddaughter/female-female` | ⛔ |
| _ENT_0_female was sick. He stayed home from school and his grandmother, ENT_1_female, watched him. She made him chicken soup to feel better._ | train | `grandmother/female-female` | wrong pronoun. replace `he`/`his`/`him` by `she`/`her`/`her` in template | ⛔ |
| _ENT_1_female took her grandson ENT_0_female to the zoo. He loved feeding the monkeys._ | train | `grandmother/female-female` | replace `grandson`/`he` by `granddaughter`/`she` in template | ⛔ |
| _ENT_0_female went to visit his grandmother, ENT_1_female, at the nursing home. She was grateful for the company, she had n't had a family visit in months._ | train | `grandmother/female-female` | wrong pronoun. replace `he`/`his`/`him` by `she`/`her`/`her` in template | ⛔ |
| _ENT_0_female stayed with his grandmother ENT_1_female last summer on her farm. He had a great time._ | train | `grandmother/female-female` | wrong pronoun. replace `he`/`his`/`him` by `she`/`her`/`her` in template | ⛔ |
| _Worker: ENT_0_female looks just like her grandmother, ENT_1_female did as a child._ | train | `grandmother/female-female` | remove `Worker: ` from template | ⛔ |

**Comment by koustuvsinha** [comment]
Thanks @NicolasAG for opening this issue! Yes we do acknowledge certain templates are problematic due to faulty annotation. I'll mark these and cleanup the templates as you have found. Alternatively, feel free to open a PR as well :) (I'm traveling next couple of weeks so I might be late at addressing this)

**Comment by yakazimir** [comment]
(apologies if I'm not seeing it): are these amt templates available somewhere?

**Comment by koustuvsinha** [comment]
Hi @yakazimir, yes the templates are downloaded automatically from my website once you run the script, check this file for more info: clutrr/main.py

**Comment by yakazimir** [comment]
Great, thank you for the info!

**Comment by koustuvsinha** [comment]
Related to #15, closing this.
