### ISSUE TITLE
--train_tasks 1.# always generates few stories from task 1.3

### ISSUE THREAD

**Issue by NicolasAG** [facebookresearch/clutrr#5]
Hi,

I noticed that when running `python main.py` with `--train_tasks 1.2,1.4,1.6` it also generated a few stories from task 1.3.

This is the detailed command I run to reproduce the bug: `python main.py --train_tasks 1.2,1.4,1.6 --test_tasks 1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10 --train_rows 100000 --test_rows 10000 --equal --template_split`
which generated the following _training_ lines:
- 96,134 lines for relations of length 2
- 96,326 lines for relations of length 4
- 94,374 lines for relations of length 6
- 7,231 lines for relations of length 3
These numbers can be found with the following command: `cat data/.../1.2,1.4,1.6_train.csv | grep task_1.3 | wc -l`

A similar behavior is observed with `--train_tasks 1.2,1.4,1.8`.

I didn't try with other tasks than **1.**#

Thanks :)

**Comment by koustuvsinha** [comment]
Should be fixed with GLC integration #9. @NicolasAG, can you retry this on the develop branch? Closing this for now, feel free to re-open if issue persists.
